#!/usr/bin/env bash

function copy_common_files {
  cp XMLSchemas/podaci_o_placanju.xsd $1
  cp XMLSchemas/tipovi_podataka.xsd $1
}

function destination {
  mkdir -p "$1/src/main/resources/schemas"
  echo "$1/src/main/resources/schemas"
}

# Setup central bank.
cbdest=$(destination "centralna-banka")

ls XMLSchemas | grep mt | xargs -I % cp XMLSchemas/% $cbdest

copy_common_files $cbdest

#Setup firm

ls XMLSchemas | grep -Fv "mt" | xargs -I % cp XMLSchemas/% $(destination "firma")
