#!/usr/bin/env bash

function copy_commom_files {
  cp XMLSchemas/podaci_o_placanju.xsd $1
  cp XMLSchemas/tipovi_podataka.xsd $1
}

# Setup central bank.
destination=centralna-banka/src/main/resources/schemas
mkdir -p $destination

ls XMLSchemas | grep mt | xargs -I % cp XMLSchemas/% $destination

copy_commom_files $destination
